abstract class ShopStates{}
class shopinitialState extends ShopStates{}
class ChangeMode extends ShopStates{}
class changesmooth extends ShopStates{}
class ChangeModepage extends ShopStates{}
class ChangeNavBar extends ShopStates{}
class Scussecgetdata extends ShopStates{}
class Errorgetdata extends ShopStates{}
class loadingshopstates extends ShopStates{}
class Scussecgetcatigoriesdata extends ShopStates{}
class Errorgetcatigoriesdata extends ShopStates{}
class ScussecgetFavoritesdata extends ShopStates{}
class ErrorgetFavoritesdata extends ShopStates{}
class changefavoritecolor extends ShopStates{}
class ErrorgetFavoritesdataM extends ShopStates{}
class ScussecgetFavoritesdataM extends ShopStates{}
class Loadingfavorites extends ShopStates{}
class ErrorgetUserProfile extends ShopStates{}
class ScussecgetUserProfile extends ShopStates{}
class LoadinggetUserProfile extends ShopStates{}
class Ispassword extends ShopStates{}
class ScussecRegisterUserProfile extends ShopStates{}
class ErorrRegisterUserProfile extends ShopStates{}
